global:
  scrape_interval:     15s # Default scrape interval

scrape_configs:
  - job_name: 'tweetapp' # Job to scrape Prometheus metrics
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['host.docker.internal:8081']
